### ISSUE TITLE
#PROGRESS 4 - MEMBUAT CODE KIRIM NOTIFIKASI KE TELEGRAM

### ISSUE THREAD

**Issue by ayunisari1406** [daniakiki/project-akhir-SmokeDetector#21]
Mmebuat program codingan untuk memberikan notifikasi ke telegram

**Comment by daniakiki** [comment]
#include <UniversalTelegramBot.h> 

//bottoken dan chat id telegram 
#define BOTtoken "5743586869:AAGrdUVLEmPp5xkZvCUiuGuQzQNpqI7pgNk" 
#define CHAT_ID "-979754581"

UniversalTelegramBot bot(BOTtoken, client);

void setup(){
  bot.sendMessage(CHAT_ID, "HALLO SELAMAT DATANG DI SMARTSTAY HOTEL");
}

void myTimerEvent(){
if(air_quality <= 300 && state!=1){
  state = 1;
  bot.sendMessage(CHAT_ID, "KONDISI RUANGAN AMAN DARI ASAP ROKOK");
  }

 if(air_quality >300 && air_quality <= 400 && state!=2){
  state = 2;
  bot.sendMessage(CHAT_ID, "WARNING! KONDISI RUANGAN TERDAPAT ASAP ROKOK");
  }
 if(air_quality >400 && state!= 3){
  state = 3;
  bot.sendMessage(CHAT_ID, "TINGGALKAN RUANGAN!! KONDISI RUANGAN BANYAK TERDAPAT ASAP ROKOK");
  }
}

// Handle what happens when you receive new messages
void handleNewMessages(int numNewMessages) {
  Serial.println("handleNewMessages");
  Serial.println(String(numNewMessages));

  for (int i=0; i<numNewMessages; i++) {
    // Chat id of the requester
    String chat_id = String(bot.messages[i].chat_id);
    Serial.println(chat_id);
    if (chat_id != CHAT_ID){
      bot.sendMessage(chat_id, "Unauthorized user", "");
      continue;
    }
    // Print the received message
    String text = bot.messages[i].text;
    Serial.println(text);
  }
}

// Checks for new messages every 1 second.
int botRequestDelay = 1000;
unsigned long lastTimeBotRan;

void loop(){ 
    
    if (millis() > lastTimeBotRan + botRequestDelay)  {
    int numNewMessages = bot.getUpdates(bot.last_message_received + 1);

    while(numNewMessages) {
      Serial.println("got response");
      handleNewMessages(numNewMessages);
      numNewMessages = bot.getUpdates(bot.last_message_received + 1);
    }
    lastTimeBotRan = millis();
  }
  
    Blynk.run();
    timer.run();
    WIFIloop(); 
}
