### ISSUE TITLE
#PROGRESS 4 - MEMBUAT CODE GABUNGAN PROYEK AKHIR

### ISSUE THREAD

**Issue by ayunisari1406** [daniakiki/project-akhir-SmokeDetector#22]
Menngabungkan semua program codingan yang telah dibuat

**Comment by akbarfadila** [comment]
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <UniversalTelegramBot.h>  
#include <ArduinoJson.h>
#include "MQ135.h"
#include <analogWrite.h>
#include <BlynkSimpleEsp32.h>

//Dilakukan definisi BLYNK_TEMPLATE_ID, BLYNK_TEMPLATE_NAME, dan BLYNK_AUTH_TOKEN untuk menghubungkan ke server Blynk.
#define BLYNK_PRINT Serial
#define BLYNK_TEMPLATE_ID "TMPL6sVnqvd-q"
#define BLYNK_TEMPLATE_NAME "FINAL PROJECT"
#define BLYNK_AUTH_TOKEN "Iw72qVjDvYYoK3WdAQpmB9mEDPxiMqmF"


BlynkTimer timer;

float air_quality;
int R = 32;
int G = 33 ;
int B = 25;

#define SENSOR 34
#define BUZZER 14

#define BOTtoken "6077759638:AAHwsXvfUfEwIaRpXUsQ82Z169uJrLCfNbw" 
#define CHAT_ID "686300946"

WiFiClientSecure client;
UniversalTelegramBot bot(BOTtoken, client);

const char* ssid = "ALIF";
const char* password = "alifsofyan02";

// Checks for new messages every 1 second.
int botRequestDelay = 1000;
unsigned long lastTimeBotRan;

void output(){
  Blynk.virtualWrite(V0, air_quality);

  if(air_quality <= 150){
  Blynk.virtualWrite(V3, 1);
  setColor(0, 255, 0);//HIJAU
}else{
  Blynk.virtualWrite(V3, 0); 
  digitalWrite(G, LOW);
}
if(air_quality >150 && air_quality <= 300){
  digitalWrite(BUZZER, HIGH);
  delay(200);
  digitalWrite(BUZZER, LOW);
  delay(200);
  setColor(255,100,0); //KUNING
  Blynk.virtualWrite(V4, 1);
}else{
  digitalWrite(B, LOW);
  digitalWrite(BUZZER, HIGH);
  Blynk.virtualWrite(V4, 0);
}
if(air_quality >300){ 
  digitalWrite(BUZZER, HIGH);
  delay(700);
  digitalWrite(BUZZER, LOW);
  delay(700);
  setColor(255,0,0); //MERAH
  Blynk.virtualWrite(V5, 1);
}else{
  digitalWrite(BUZZER, HIGH);
  digitalWrite(R, LOW);
  Blynk.virtualWrite(V5, 0);
 }
}

int state = 0;

void myTimerEvent(){
  if(air_quality <= 150 && state!=1){
  state = 1;
  bot.sendMessage(CHAT_ID, "KONDISI RUANGAN AMAN DARI ASAP ROKOK");
  }

 if(air_quality >150 && air_quality <= 300 && state!=2){
  state = 2;
  bot.sendMessage(CHAT_ID, "WARNING! KONDISI RUANGAN TERDAPAT ASAP ROKOK");
  }

 if(air_quality >300 && state!=3){
  state = 3;
  bot.sendMessage(CHAT_ID, "TINGGALKAN RUANGAN!! KONDISI RUANGAN BANYAK TERDAPAT ASAP ROKOK");
  }  
}


void setup(){
  Serial.begin(115200);
  Blynk.begin(BLYNK_AUTH_TOKEN, ssid, password);
  timer.setInterval(1000L, myTimerEvent);
  timer.setInterval(1000L, output);
  pinMode(34, INPUT);
  pinMode(R, OUTPUT);
  pinMode(G, OUTPUT);
  pinMode(B, OUTPUT);
  pinMode(BUZZER, OUTPUT);
  digitalWrite(BUZZER,HIGH);

  // Connect to Wi-Fi
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  #ifdef ESP32
    client.setCACert(TELEGRAM_CERTIFICATE_ROOT); // Add root certificate for api.telegram.org
  #endif
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Serial.println("Connecting to WiFi..");
  }
  // Print ESP32 Local IP Address
  Serial.println(WiFi.localIP());

  bot.sendMessage(CHAT_ID, "hallo selamat datang di hotel Bintang");
}
 

// Handle what happens when you receive new messages
void handleNewMessages(int numNewMessages) {
  Serial.println("handleNewMessages");
  Serial.println(String(numNewMessages));

  for (int i=0; i<numNewMessages; i++) {
    // Chat id of the requester
    String chat_id = String(bot.messages[i].chat_id);
    Serial.println(chat_id);
    if (chat_id != CHAT_ID){
      bot.sendMessage(chat_id, "Unauthorized user", "");
      continue;
    }
    
    // Print the received message
    String text = bot.messages[i].text;
    Serial.println(text);
  }
}

void loop(){
  MQ135 gasSensor = MQ135(SENSOR);
   air_quality = gasSensor.getPPM();
    Serial.print("Air Quality: ");  
    Serial.print(air_quality);
    Serial.println("  PPM");   
    Serial.println("Waiting...");
    delay(2000);

    
if (millis() > lastTimeBotRan + botRequestDelay)  {
    int numNewMessages = bot.getUpdates(bot.last_message_received + 1);

    while(numNewMessages) {
      Serial.println("got response");
      handleNewMessages(numNewMessages);
      numNewMessages = bot.getUpdates(bot.last_message_received + 1);
    }
    lastTimeBotRan = millis();
  }
  Blynk.run();
   timer.run(); // Initiates BlynkTimer
}
void setColor(int red, int green, int blue)
{
  analogWrite(R, red);//MENULIS DATA ANALOG KE PIN LED MERAH
  analogWrite(G, green);//MENULIS DATA ANALOG KE PIN LED KUNING
  analogWrite(B, blue);//MENULIS DATA ANALOG KE PIN LED BIRU
}

**Comment by ayunisari1406** [comment]
//include library
#include "MQ135.h"  
#include <WiFi.h>
#include <WiFiManager.h>
#include <WiFiClientSecure.h>
#include <BlynkSimpleEsp32.h>
#include <UniversalTelegramBot.h> 
#include <analogWrite.h>
#include <ArduinoJson.h>

//bottoken dan chat id telegram 
#define BOTtoken "5743586869:AAGrdUVLEmPp5xkZvCUiuGuQzQNpqI7pgNk" 
#define CHAT_ID "-979754581"

WiFiManager wm;
WiFiClientSecure client;
UniversalTelegramBot bot(BOTtoken, client);

#define BLYNK_PRINT Serial
#define BLYNK_TEMPLATE_ID "TMPL6vAySAyTD"
#define BLYNK_TEMPLATE_NAME "PROJEK AKHIR  MYSKILL"
#define BLYNK_AUTH_TOKEN "AObSAKeRrFwzuIn_gJrw_NMWhvTyno9E"
BlynkTimer timer;

char ssid[1]; 
char pass[1]; 

#define SENSOR 34 //deklarasi pin sensor MQ135
#define BUZZER 14 //deklarasi pin buzzer

float air_quality;
int R = 32;
int BY = 25;
int G = 33;

void setup(){
  Serial.begin(9600);
  WIFIsetup();
  Blynk.begin(BLYNK_AUTH_TOKEN, ssid, pass);
  timer.setInterval(1000L, myTimerEvent);
  timer.setInterval(1000L, output);

  pinMode(R, OUTPUT);
  pinMode(BY, OUTPUT);
  pinMode(G, OUTPUT);

  pinMode(SENSOR, INPUT);
  pinMode(BUZZER, OUTPUT);
  digitalWrite(BUZZER,HIGH);

  client.setCACert(TELEGRAM_CERTIFICATE_ROOT);
  bot.sendMessage(CHAT_ID, "HALLO SELAMAT DATANG DI SMARTSTAY HOTEL");
}

void setColor(int redValue, int greenValue, int blueValue){
  analogWrite(R , redValue);
  analogWrite(G , greenValue);
  analogWrite(BY, blueValue);
}

void output(){
  Blynk.virtualWrite(V0, air_quality);
  
  if(air_quality <= 300){
    Blynk.virtualWrite(V3, 1);
    setColor(0, 255, 0);//HIJAU
  }else{
    Blynk.virtualWrite(V3, 0); 
    digitalWrite(G, LOW);
  }

  if(air_quality >300 && air_quality <= 400){
    digitalWrite(BUZZER, HIGH);
    delay(200);
    digitalWrite(BUZZER, LOW);
    delay(200);
    setColor(255,100,0); //KUNING
    Blynk.virtualWrite(V4, 1);
  }else{
    digitalWrite(BY, LOW);
    digitalWrite(BUZZER, HIGH);
    Blynk.virtualWrite(V4, 0);
  }

  if(air_quality >400){ 
    digitalWrite(BUZZER, HIGH);
    delay(500);
    digitalWrite(BUZZER, LOW);
    delay(500);
    setColor(255,0,0); //MERAH
    Blynk.virtualWrite(V5, 1);
  }else{
    digitalWrite(BUZZER, HIGH);
    digitalWrite(R, LOW);
    Blynk.virtualWrite(V5, 0);
  }
}

int state = 0;
int counter = 0;

void myTimerEvent(){
    MQ135 gasSensor = MQ135(SENSOR);
    air_quality = gasSensor.getPPM();
    Serial.print("Air Quality: ");  
    Serial.print(air_quality);
    Serial.println("  PPM");   
    Serial.println("Waiting...");
    
  if(counter < 15 && state == 3){
  counter++;
  }else if (counter >=15){
  counter = 0; state = 0;
  Serial.print("state");
}
  if(air_quality <= 300 && state!=1){
  state = 1;
  bot.sendMessage(CHAT_ID, "KONDISI RUANGAN AMAN DARI ASAP ROKOK");
  }

 if(air_quality >300 && air_quality <= 400 && state!=2){
  state = 2;
  bot.sendMessage(CHAT_ID, "WARNING! KONDISI RUANGAN TERDAPAT ASAP ROKOK");
  }
 if(air_quality >400 && state!= 3){
  state = 3;
  bot.sendMessage(CHAT_ID, "TINGGALKAN RUANGAN!! KONDISI RUANGAN BANYAK TERDAPAT ASAP ROKOK");
  }
}

// Handle what happens when you receive new messages
void handleNewMessages(int numNewMessages) {
  Serial.println("handleNewMessages");
  Serial.println(String(numNewMessages));

  for (int i=0; i<numNewMessages; i++) {
    // Chat id of the requester
    String chat_id = String(bot.messages[i].chat_id);
    Serial.println(chat_id);
    if (chat_id != CHAT_ID){
      bot.sendMessage(chat_id, "Unauthorized user", "");
      continue;
    }
    // Print the received message
    String text = bot.messages[i].text;
    Serial.println(text);
  }
}

// Checks for new messages every 1 second.
int botRequestDelay = 1000;
unsigned long lastTimeBotRan;

void loop(){ 
    
    if (millis() > lastTimeBotRan + botRequestDelay)  {
    int numNewMessages = bot.getUpdates(bot.last_message_received + 1);

    while(numNewMessages) {
      Serial.println("got response");
      handleNewMessages(numNewMessages);
      numNewMessages = bot.getUpdates(bot.last_message_received + 1);
    }
    lastTimeBotRan = millis();
  }
  
    Blynk.run();
    timer.run();
    WIFIloop(); 
}
